- name: create cron scripts from templates
  template:
    src: "cron/{{ item }}.j2"
    dest: "{{ GALAXY_HOME }}/cron/{{ item }}"
    mode: 0755
  with_items:
      - "backup_pg_database.sh"
      - "backup_galaxy_maintained_files.sh"
      - "cleanup_datasets.sh"
      - "set_user_disk_usage.sh"
      - "updateucsc.sh"
      - "processTaxonomy_cron.sh"

- name: create scripts directory
  file: dest={{ GALAXY_HOME }}/scripts/ state=directory

- name: create scripts logs directory
  file: dest={{ GALAXY_HOME }}/scripts/logs state=directory

- name: set MAILTO in crontab
  ansible.builtin.cron:
    name: "MAILTO"
    minute: "MAILTO={{ crontab_mailto }}"
    hour: ""
    day: ""
    month: ""
    weekday: ""
    job: ""

- name: crontab entry to backup Galaxy database
  ansible.builtin.cron:
    name: "backup galaxy database"
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "scl enable rh-postgresql96 -- {{ GALAXY_HOME }}cron/backup_pg_database.sh"

- name: crontab entry to backup Galaxy maintained files
  ansible.builtin.cron:
    name: "backup galaxy maintained files"
    minute: "0"
    hour: "1"
    day: "*"
    month: "*"
    weekday: "*"
    job: "{{ GALAXY_HOME }}cron/backup_galaxy_maintained_files.sh"

- name: crontab entry to cleanup datasets
  ansible.builtin.cron:
    name: "cleanup galaxy datasets"
    minute: "0"
    hour: "2"
    day: "*"
    month: "*"
    weekday: "*"
    job: "export PATH=/usr/local/bin:$PATH; {{ GALAXY_HOME }}/cron/cleanup_datasets.sh"

- name: crontab entry to set Galaxy user disk usage
  ansible.builtin.cron:
    name: "set galaxy user disk usage"
    minute: "0"
    hour: "4"
    day: "*"
    month: "*"
    weekday: "*"
    job: "export PATH=/usr/local/bin:$PATH; {{ GALAXY_HOME }}/cron/set_user_disk_usage.sh"

- name: crontab entry to cleanup Galaxy temp files
  ansible.builtin.cron:
    name: "cleanup galaxy tempfiles"
    minute: "20"
    hour: "4"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/tmpwatch --atime --dirmtime 168 --exclude-pattern \"{{ tmp_dir }}/.nfs*\" {{ tmp_dir }}"

- name: crontab entry to cleanup Galaxy new_file_path files
  ansible.builtin.cron:
    name: "cleanup galaxy tempfiles"
    minute: "40"
    hour: "4"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/tmpwatch --atime --dirmtime 168 {{ new_file_path }}"

- name: crontab entry to cleanup exported Galaxy files
  ansible.builtin.cron:
    name: "cleanup exported galaxy files"
    minute: "0"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/tmpwatch --atime --dirmtime 168 {{ export_dir }}"

- name: crontab entry to cleanup log files
  ansible.builtin.cron:
    name: "cleanup galaxy log files"
    minute: "15"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/sbin/logrotate {{ GALAXY_HOME }}/config/logrotate/logrotate.conf --state {{ GALAXY_HOME }}/config/logrotate/logrotate-state"

- name: crontab entry to update ncbi taxonomy
  ansible.builtin.cron:
    name: "update ncbi taxonomy"
    minute: "30"
    hour: "5"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/bin/sh {{ GALAXY_HOME }}/cron/processTaxonomy_cron.sh"
    disabled: "{{ env == 'development' }}"

- name: crontab entry to update ucsc genomes
  ansible.builtin.cron:
    name: "update ucsc genomes"
    minute: "0"
    hour: "6"
    day: "*"
    month: "*"
    weekday: "mon-sat"
    job: "{{ GALAXY_HOME }}cron/updateucsc.sh >> {{ GALAXY_HOME }}/../logs/updateucsc.log"
    disabled: "{{ env == 'development' }}"
